version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_northwind
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSeguro123!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always

volumes:
  mssql-data:
    driver: local
